### ISSUE TITLE
PHP 8.1 support?

### ISSUE THREAD

**Issue by eli-s-r** [keapgeek/laravel-keap#2]
Would it be possible for this library to support PHP 8.1 as its minimum version instead of 8.2? Upgrading to 8.2 is not possible for us right now, so we would be unable to use this package.

**Comment by azzarip** [comment]
I will do a quick check if it is possible to downgrade without problems! In case I will change the requirements

**Comment by azzarip** [comment]
I added support for php 8.1

**Comment by eli-s-r** [comment]
Thanks @azzarip!
